security:
  user:
    name: admin
    password: admin
  basic:
    enabled: true
management:
  security:
    enabled: false
logging:
  level:
    io:
      pivotal: DEBUG
greeting:
  displayFortune: true
quoteServiceURL: http://quote-service-dev.cfapps.io/quote
